"""add action

Revision ID: ef95631b12b4
Revises: ca0493d8654f
Create Date: 2024-02-24 10:59:12.321590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef95631b12b4'
down_revision = 'ca0493d8654f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint('attendances_student_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('attendances_class_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('class_students', schema=None) as batch_op:
        batch_op.drop_constraint('class_students_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('class_students_class_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('classes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('classes_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('class_students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('class_students_class_id_fkey', 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key('class_students_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('attendances_class_id_fkey', 'classes', ['class_id'], ['id'])
        batch_op.create_foreign_key('attendances_student_id_fkey', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###
